// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

export function Bootstrap(): $CancellablePromise<$models.AppSnapshot> {
    return $Call.ByID(1077023444).then(($result: any) => {
        return $$createType0($result);
    });
}

export function ChooseFile(kind: string): $CancellablePromise<string> {
    return $Call.ByID(180571057, kind);
}

export function CopyAddress(endpointKey: string): $CancellablePromise<void> {
    return $Call.ByID(3042061561, endpointKey);
}

export function CopyDiagnostics(): $CancellablePromise<void> {
    return $Call.ByID(785777809);
}

export function OpenLogs(): $CancellablePromise<void> {
    return $Call.ByID(2130219693);
}

export function OpenRule(endpointKey: string): $CancellablePromise<void> {
    return $Call.ByID(2680216000, endpointKey);
}

export function Refresh(): $CancellablePromise<void> {
    return $Call.ByID(171967693);
}

export function SaveSettings(input: $models.SettingsInput): $CancellablePromise<void> {
    return $Call.ByID(2365899470, input);
}

export function SetFavorite(endpointKey: string, favorite: boolean): $CancellablePromise<void> {
    return $Call.ByID(217334146, endpointKey, favorite);
}

export function StopAll(): $CancellablePromise<void> {
    return $Call.ByID(2887848093);
}

export function ToggleRule(endpointKey: string): $CancellablePromise<void> {
    return $Call.ByID(3186708440, endpointKey);
}

export function UpdateRule(endpointKey: string, patch: $models.RulePatch): $CancellablePromise<void> {
    return $Call.ByID(293323825, endpointKey, patch);
}

export function Wake(targetKey: string): $CancellablePromise<void> {
    return $Call.ByID(4160406262, targetKey);
}

// Private type creation functions
const $$createType0 = $models.AppSnapshot.createFrom;
