// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as manager$0 from "../manager/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as model$0 from "../model/models.js";

export class AppSnapshot {
    "revision": number;
    "version": string;
    "syncState": string;
    "syncMessage": string;
    "lastSyncedAt": string;
    "node": NodeSnapshot;
    "summary": AppSummary;
    "services": ServiceSnapshot[];
    "wakeTargets": WakeTargetSnapshot[];
    "settings": SettingsSnapshot;

    /** Creates a new AppSnapshot instance. */
    constructor($$source: Partial<AppSnapshot> = {}) {
        if (!("revision" in $$source)) {
            this["revision"] = 0;
        }
        if (!("version" in $$source)) {
            this["version"] = "";
        }
        if (!("syncState" in $$source)) {
            this["syncState"] = "";
        }
        if (!("syncMessage" in $$source)) {
            this["syncMessage"] = "";
        }
        if (!("lastSyncedAt" in $$source)) {
            this["lastSyncedAt"] = "";
        }
        if (!("node" in $$source)) {
            this["node"] = (new NodeSnapshot());
        }
        if (!("summary" in $$source)) {
            this["summary"] = (new AppSummary());
        }
        if (!("services" in $$source)) {
            this["services"] = [];
        }
        if (!("wakeTargets" in $$source)) {
            this["wakeTargets"] = [];
        }
        if (!("settings" in $$source)) {
            this["settings"] = (new SettingsSnapshot());
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new AppSnapshot instance from a string or object.
     */
    static createFrom($$source: any = {}): AppSnapshot {
        const $$createField5_0 = $$createType0;
        const $$createField6_0 = $$createType1;
        const $$createField7_0 = $$createType3;
        const $$createField8_0 = $$createType5;
        const $$createField9_0 = $$createType6;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("node" in $$parsedSource) {
            $$parsedSource["node"] = $$createField5_0($$parsedSource["node"]);
        }
        if ("summary" in $$parsedSource) {
            $$parsedSource["summary"] = $$createField6_0($$parsedSource["summary"]);
        }
        if ("services" in $$parsedSource) {
            $$parsedSource["services"] = $$createField7_0($$parsedSource["services"]);
        }
        if ("wakeTargets" in $$parsedSource) {
            $$parsedSource["wakeTargets"] = $$createField8_0($$parsedSource["wakeTargets"]);
        }
        if ("settings" in $$parsedSource) {
            $$parsedSource["settings"] = $$createField9_0($$parsedSource["settings"]);
        }
        return new AppSnapshot($$parsedSource as Partial<AppSnapshot>);
    }
}

export class AppSummary {
    "total": number;
    "running": number;
    "favorites": number;
    "errors": number;
    "activeConnections": number;

    /** Creates a new AppSummary instance. */
    constructor($$source: Partial<AppSummary> = {}) {
        if (!("total" in $$source)) {
            this["total"] = 0;
        }
        if (!("running" in $$source)) {
            this["running"] = 0;
        }
        if (!("favorites" in $$source)) {
            this["favorites"] = 0;
        }
        if (!("errors" in $$source)) {
            this["errors"] = 0;
        }
        if (!("activeConnections" in $$source)) {
            this["activeConnections"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new AppSummary instance from a string or object.
     */
    static createFrom($$source: any = {}): AppSummary {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new AppSummary($$parsedSource as Partial<AppSummary>);
    }
}

export class NodeSnapshot {
    "connected": boolean;
    "version": string;
    "apiBase": string;
    "message": string;

    /** Creates a new NodeSnapshot instance. */
    constructor($$source: Partial<NodeSnapshot> = {}) {
        if (!("connected" in $$source)) {
            this["connected"] = false;
        }
        if (!("version" in $$source)) {
            this["version"] = "";
        }
        if (!("apiBase" in $$source)) {
            this["apiBase"] = "";
        }
        if (!("message" in $$source)) {
            this["message"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new NodeSnapshot instance from a string or object.
     */
    static createFrom($$source: any = {}): NodeSnapshot {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new NodeSnapshot($$parsedSource as Partial<NodeSnapshot>);
    }
}

export class RulePatch {
    "listenPort": number;
    "kind": model$0.ServiceKind;
    "webScheme": string;

    /** Creates a new RulePatch instance. */
    constructor($$source: Partial<RulePatch> = {}) {
        if (!("listenPort" in $$source)) {
            this["listenPort"] = 0;
        }
        if (!("kind" in $$source)) {
            this["kind"] = model$0.ServiceKind.$zero;
        }
        if (!("webScheme" in $$source)) {
            this["webScheme"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new RulePatch instance from a string or object.
     */
    static createFrom($$source: any = {}): RulePatch {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new RulePatch($$parsedSource as Partial<RulePatch>);
    }
}

export class ServiceSnapshot {
    "endpointKey": string;
    "name": string;
    "host": string;
    "targetPort": number;
    "targetAddress": string;
    "listenPort": number;
    "localAddress": string;
    "kind": model$0.ServiceKind;
    "webScheme": string;
    "favorite": boolean;
    "available": boolean;
    "running": boolean;
    "state": manager$0.State;
    "stateLabel": string;
    "message": string;
    "activeConnections": number;
    "canOpen": boolean;

    /** Creates a new ServiceSnapshot instance. */
    constructor($$source: Partial<ServiceSnapshot> = {}) {
        if (!("endpointKey" in $$source)) {
            this["endpointKey"] = "";
        }
        if (!("name" in $$source)) {
            this["name"] = "";
        }
        if (!("host" in $$source)) {
            this["host"] = "";
        }
        if (!("targetPort" in $$source)) {
            this["targetPort"] = 0;
        }
        if (!("targetAddress" in $$source)) {
            this["targetAddress"] = "";
        }
        if (!("listenPort" in $$source)) {
            this["listenPort"] = 0;
        }
        if (!("localAddress" in $$source)) {
            this["localAddress"] = "";
        }
        if (!("kind" in $$source)) {
            this["kind"] = model$0.ServiceKind.$zero;
        }
        if (!("webScheme" in $$source)) {
            this["webScheme"] = "";
        }
        if (!("favorite" in $$source)) {
            this["favorite"] = false;
        }
        if (!("available" in $$source)) {
            this["available"] = false;
        }
        if (!("running" in $$source)) {
            this["running"] = false;
        }
        if (!("state" in $$source)) {
            this["state"] = manager$0.State.$zero;
        }
        if (!("stateLabel" in $$source)) {
            this["stateLabel"] = "";
        }
        if (!("message" in $$source)) {
            this["message"] = "";
        }
        if (!("activeConnections" in $$source)) {
            this["activeConnections"] = 0;
        }
        if (!("canOpen" in $$source)) {
            this["canOpen"] = false;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ServiceSnapshot instance from a string or object.
     */
    static createFrom($$source: any = {}): ServiceSnapshot {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new ServiceSnapshot($$parsedSource as Partial<ServiceSnapshot>);
    }
}

export class SettingsSnapshot {
    "launchAtLogin": boolean;
    "startFavoritesOnLaunch": boolean;
    "credentialFile": string;
    "rdpLauncher": string;
    "vncLauncher": string;
    "refreshMinutes": number;
    "themeMode": string;

    /** Creates a new SettingsSnapshot instance. */
    constructor($$source: Partial<SettingsSnapshot> = {}) {
        if (!("launchAtLogin" in $$source)) {
            this["launchAtLogin"] = false;
        }
        if (!("startFavoritesOnLaunch" in $$source)) {
            this["startFavoritesOnLaunch"] = false;
        }
        if (!("credentialFile" in $$source)) {
            this["credentialFile"] = "";
        }
        if (!("rdpLauncher" in $$source)) {
            this["rdpLauncher"] = "";
        }
        if (!("vncLauncher" in $$source)) {
            this["vncLauncher"] = "";
        }
        if (!("refreshMinutes" in $$source)) {
            this["refreshMinutes"] = 0;
        }
        if (!("themeMode" in $$source)) {
            this["themeMode"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new SettingsSnapshot instance from a string or object.
     */
    static createFrom($$source: any = {}): SettingsSnapshot {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new SettingsSnapshot($$parsedSource as Partial<SettingsSnapshot>);
    }
}

export const SettingsInput = SettingsSnapshot;
export type SettingsInput = SettingsSnapshot;

export class WakeTargetSnapshot {
    "targetKey": string;
    "name": string;
    "maskedMAC": string;
    "online": boolean;

    /** Creates a new WakeTargetSnapshot instance. */
    constructor($$source: Partial<WakeTargetSnapshot> = {}) {
        if (!("targetKey" in $$source)) {
            this["targetKey"] = "";
        }
        if (!("name" in $$source)) {
            this["name"] = "";
        }
        if (!("maskedMAC" in $$source)) {
            this["maskedMAC"] = "";
        }
        if (!("online" in $$source)) {
            this["online"] = false;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new WakeTargetSnapshot instance from a string or object.
     */
    static createFrom($$source: any = {}): WakeTargetSnapshot {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new WakeTargetSnapshot($$parsedSource as Partial<WakeTargetSnapshot>);
    }
}

// Private type creation functions
const $$createType0 = NodeSnapshot.createFrom;
const $$createType1 = AppSummary.createFrom;
const $$createType2 = ServiceSnapshot.createFrom;
const $$createType3 = $Create.Array($$createType2);
const $$createType4 = WakeTargetSnapshot.createFrom;
const $$createType5 = $Create.Array($$createType4);
const $$createType6 = SettingsSnapshot.createFrom;
